
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KoG
 */
public class LaptopBuilder extends javax.swing.JPanel {
    String hd = "";
    String ram = "";
    String cpu = "";
    String gpu1 = "";
    String gpu2 = "";
    
    /**
     * Creates new form ComputerBuilder
     */
    public LaptopBuilder() {
        initComponents();
        
        gpuSingle.setSelected(true);
        
        cpu = cpuDropdown.getSelectedItem().toString();
        gpu1 = gpuDropdown1.getSelectedItem().toString();
        gpu2 = gpuDropdown2.getSelectedItem().toString();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hdGroup = new javax.swing.ButtonGroup();
        ramGroup = new javax.swing.ButtonGroup();
        gpuGroup = new javax.swing.ButtonGroup();
        topLabel = new javax.swing.JLabel();
        hdLabel = new javax.swing.JLabel();
        sata4gb = new javax.swing.JRadioButton();
        ssd256gb = new javax.swing.JRadioButton();
        ssd512gb = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        ramLabel = new javax.swing.JLabel();
        ddr3gb2 = new javax.swing.JRadioButton();
        ddr3gb4 = new javax.swing.JRadioButton();
        ddr3gb8 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cpuDropdown = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        gpuSingle = new javax.swing.JRadioButton();
        gpuDouble = new javax.swing.JRadioButton();
        gpuDropdown1 = new javax.swing.JComboBox<>();
        gpuDropdown2 = new javax.swing.JComboBox<>();

        topLabel.setText("Build a laptop");

        hdLabel.setText("Hard Drive");

        hdGroup.add(sata4gb);
        sata4gb.setText("4TB SATA");
        sata4gb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sata4gbActionPerformed(evt);
            }
        });

        hdGroup.add(ssd256gb);
        ssd256gb.setText("256GB SSD");
        ssd256gb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssd256gbActionPerformed(evt);
            }
        });

        hdGroup.add(ssd512gb);
        ssd512gb.setText("512GB SSD");
        ssd512gb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssd512gbActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        ramLabel.setText("RAM");

        ramGroup.add(ddr3gb2);
        ddr3gb2.setText("2GB DDR3");
        ddr3gb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddr3gb2ActionPerformed(evt);
            }
        });

        ramGroup.add(ddr3gb4);
        ddr3gb4.setText("4GB DDR3");
        ddr3gb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddr3gb4ActionPerformed(evt);
            }
        });

        ramGroup.add(ddr3gb8);
        ddr3gb8.setText("8GB DDR3");
        ddr3gb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddr3gb8ActionPerformed(evt);
            }
        });

        jLabel1.setText("CPU");

        cpuDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AMD Athalon x8", "AMD Athalon x4", "AMD Athalon x2", "Intel i7-5820K (6 core)", "Intel i7-5930K (6 core)", "Intel i7-5960K (8 core)", "Intel i5-3330K (4 core)", "Intel i5-3830K (6 core)", "Intel i5-4330K (4 core)", "Intel i5-4370K (8 core)" }));
        cpuDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpuDropdownActionPerformed(evt);
            }
        });

        jLabel2.setText("GPU");

        gpuGroup.add(gpuSingle);
        gpuSingle.setText("Single");
        gpuSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpuSingleActionPerformed(evt);
            }
        });

        gpuGroup.add(gpuDouble);
        gpuDouble.setText("Double");
        gpuDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpuDoubleActionPerformed(evt);
            }
        });

        gpuDropdown1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NVidia GE Force Titan X", "NVidia GE Force 980-TI", "NVidia GE Force 750", "NVidia GE Force 760", "NVidia GE Force 770", "NVidia GE Force 780", "NVidia GE Force 790", "NVidia GE Force 650", "NVidia GE Force 660", "NVidia GE Force 670", "NVidia GE Force 680", "NVidia GE Force 690" }));
        gpuDropdown1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpuDropdown1ActionPerformed(evt);
            }
        });

        gpuDropdown2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NVidia GE Force Titan X", "NVidia GE Force 980-TI", "NVidia GE Force 750", "NVidia GE Force 760", "NVidia GE Force 770", "NVidia GE Force 780", "NVidia GE Force 790", "NVidia GE Force 650", "NVidia GE Force 660", "NVidia GE Force 670", "NVidia GE Force 680", "NVidia GE Force 690" }));
        gpuDropdown2.setEnabled(false);
        gpuDropdown2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpuDropdown2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ddr3gb8)
                            .addComponent(ddr3gb4)
                            .addComponent(ssd512gb)
                            .addComponent(sata4gb)
                            .addComponent(topLabel)
                            .addComponent(hdLabel)
                            .addComponent(ssd256gb)
                            .addComponent(ramLabel)
                            .addComponent(ddr3gb2)
                            .addComponent(jLabel1)
                            .addComponent(cpuDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gpuSingle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gpuDouble))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gpuDropdown1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gpuDropdown2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sata4gb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ssd256gb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ssd512gb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ramLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ddr3gb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ddr3gb4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ddr3gb8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpuDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpuSingle)
                    .addComponent(gpuDouble))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpuDropdown1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuDropdown2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        StringBuilder summary = new StringBuilder();
        
        if (hd.length() == 0 || ram.length() == 0) { 
            summary.append("Error!");
            
            summary.append((hd.length() == 0) ? "\nYou must select a hard drive!" : "");
            summary.append((ram.length() == 0) ? "\nYou must select RAM!" : "");
            
            JOptionPane.showMessageDialog(this, summary, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        summary.append("Summary:\nHardDrive: ").append(hd)
                .append("\nRAM: ").append(ram)
                .append("\nCPU: ").append(cpu);
        
        if (gpuSingle.isSelected()) {
            summary.append("\nGPU: ").append(gpu1);
        } else {
            summary.append("\nGPU 1: ").append(gpu1)
                    .append("\nGPU 2: ").append(gpu2);
        }
        
        JOptionPane.showMessageDialog(this, summary);
        
        
        
        
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void sata4gbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sata4gbActionPerformed
        hd = "4GB SATA";
    }//GEN-LAST:event_sata4gbActionPerformed

    private void ssd256gbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssd256gbActionPerformed
        hd = "256GB SSD";
    }//GEN-LAST:event_ssd256gbActionPerformed

    private void ssd512gbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssd512gbActionPerformed
        hd = "512GB SSD";
    }//GEN-LAST:event_ssd512gbActionPerformed

    private void ddr3gb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddr3gb2ActionPerformed
        ram = "2GB DDR3";
    }//GEN-LAST:event_ddr3gb2ActionPerformed

    private void ddr3gb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddr3gb4ActionPerformed
        ram = "4GB DDR3";
    }//GEN-LAST:event_ddr3gb4ActionPerformed

    private void ddr3gb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddr3gb8ActionPerformed
        ram = "8GB DDR3";
    }//GEN-LAST:event_ddr3gb8ActionPerformed

    private void cpuDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpuDropdownActionPerformed
        cpu = cpuDropdown.getSelectedItem().toString();
    }//GEN-LAST:event_cpuDropdownActionPerformed

    private void gpuDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpuDoubleActionPerformed
        gpuDropdown2.setEnabled(true);
    }//GEN-LAST:event_gpuDoubleActionPerformed

    private void gpuDropdown1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpuDropdown1ActionPerformed
        gpu1 = gpuDropdown1.getSelectedItem().toString();
    }//GEN-LAST:event_gpuDropdown1ActionPerformed

    private void gpuDropdown2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpuDropdown2ActionPerformed
        gpu2 = gpuDropdown2.getSelectedItem().toString();
    }//GEN-LAST:event_gpuDropdown2ActionPerformed

    private void gpuSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpuSingleActionPerformed
        gpuDropdown2.setEnabled(false);
    }//GEN-LAST:event_gpuSingleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cpuDropdown;
    private javax.swing.JRadioButton ddr3gb2;
    private javax.swing.JRadioButton ddr3gb4;
    private javax.swing.JRadioButton ddr3gb8;
    private javax.swing.JRadioButton gpuDouble;
    private javax.swing.JComboBox<String> gpuDropdown1;
    private javax.swing.JComboBox<String> gpuDropdown2;
    private javax.swing.ButtonGroup gpuGroup;
    private javax.swing.JRadioButton gpuSingle;
    private javax.swing.ButtonGroup hdGroup;
    private javax.swing.JLabel hdLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.ButtonGroup ramGroup;
    private javax.swing.JLabel ramLabel;
    private javax.swing.JRadioButton sata4gb;
    private javax.swing.JRadioButton ssd256gb;
    private javax.swing.JRadioButton ssd512gb;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel topLabel;
    // End of variables declaration//GEN-END:variables
}
